"""
Django settings for zignal project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-mcc@@y*qg7%42w)mw44s=((ukn@e7$!!*5af1+f7xvtlz(t7i%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,mighty-wave-39560-d078d75c03f3.herokuapp.com').split(',')

# CSRF settings - trusted origins for cross-domain requests
CSRF_TRUSTED_ORIGINS = [
    'https://www.zignal.se',
    'https://zignal.se', 
    'https://mighty-wave-39560-d078d75c03f3.herokuapp.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    
    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'anymail',
    'rest_framework',
    'channels',
    
    # Local apps
    'users',
    'agents',
    'companies',
    'projects',
    'datasilo',
    'reports',
    'invitations',
    'profiles',
    'mail_receiver',
    'notifications',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'zignal.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'zignal.context_processors.settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'zignal.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'zignal'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Support for Heroku PostgreSQL
import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Cache and Redis settings

# Fix Redis URL scheme inconsistencies between local and production environments
redis_main_url = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
redis_ssl = redis_main_url.startswith('rediss://')

# Set up channel Redis URL - default to same as main Redis but with different DB
CHANNEL_REDIS_URL = os.getenv('CHANNEL_REDIS_URL', redis_main_url.replace('6379/0', '6379/3'))

# Redis settings for Celery
CELERY_RESULT_BACKEND = redis_main_url
CELERY_BROKER_URL = redis_main_url

# Redis connections need SSL settings in production
if redis_ssl:
    # SSL settings for Redis connections
    from redis.connection import ConnectionPool
    import ssl
    
    # Configure SSL settings - disable certificate verification for Heroku Redis
    REDIS_SSL_SETTINGS = {
        'ssl_cert_reqs': ssl.CERT_NONE,
        'ssl_check_hostname': False
    }
    
    # Configure Celery to use SSL for Redis
    CELERY_REDIS_BACKEND_USE_SSL = REDIS_SSL_SETTINGS
    CELERY_BROKER_USE_SSL = REDIS_SSL_SETTINGS
    
    # Apply settings to all Redis connection pools globally
    def configure_redis_ssl():
        try:
            pools = getattr(ConnectionPool, '_connection_pool_cache', {})
            for url, pool in pools.items():
                if url.startswith('rediss://'):
                    pool.connection_kwargs.update(REDIS_SSL_SETTINGS)
        except Exception as e:
            print(f"Error configuring Redis SSL pools: {str(e)}")
    
    configure_redis_ssl()

# Channel Layers
if redis_ssl:
    # In production, configure Redis with SSL settings for Channels
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [
                    {
                        'address': CHANNEL_REDIS_URL,
                        'ssl_cert_reqs': None,
                        'ssl_check_hostname': False,
                    }
                ],
            },
        },
    }
else:
    # Local development - normal config
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [CHANNEL_REDIS_URL],
            },
        },
    }

# Notification settings
NOTIFICATION_SOUND_ENABLED = os.getenv('NOTIFICATION_SOUND_ENABLED', 'True') == 'True'
NOTIFICATION_VIBRATION_ENABLED = os.getenv('NOTIFICATION_VIBRATION_ENABLED', 'True') == 'True'

# Email domain for mail receiver
EMAIL_DOMAIN = os.getenv('EMAIL_DOMAIN', 'zignal.se')
