# Generated by Django 5.2 on 2025-04-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_agent_project_or_company_not_null'),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255, unique=True)),
                ('external_meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google_meet', 'Google Meet')], max_length=20)),
                ('meeting_url', models.URLField(max_length=1000)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('transcript_raw', models.TextField(blank=True, null=True)),
                ('transcript_summary', models.TextField(blank=True, null=True)),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='meeting_transcripts/')),
                ('recording_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('meetingbaas_bot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meetingbaas_webhook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_transcripts', to='companies.company')),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_transcript', to='agents.conversation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_transcripts', to='projects.project')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Transcript',
                'verbose_name_plural': 'Meeting Transcripts',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
