# Generated by Django 5.2 on 2025-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_api_version_agent_assistant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
    ]
