# Generated by Django 5.2 on 2025-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='vector_store_file_id',
            field=models.CharField(blank=True, help_text='OpenAI Vector Store File ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='vector_store_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='vector_store_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Vector Processing'), ('processing', 'Processing for Vector Store'), ('processed', 'Added to Vector Store'), ('failed', 'Failed to Add to Vector Store'), ('skipped', 'Skipped (Unsupported Format)')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document (PDF, DOC, DOCX, TXT)'), ('spreadsheet', 'Spreadsheet (XLS, XLSX, CSV)'), ('json', 'JSON'), ('other', 'Other')], default='document', max_length=20),
        ),
    ]
