# Generated by Django 5.2 on 2025-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasilo', '0002_datafile_vector_store_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Original S3 file path that was validated to exist', max_length=512, null=True),
        ),
    ]
