# Generated by Django 5.2 on 2025-05-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasilo', '0003_datafile_original_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='original_file_path',
        ),
    ]
