# Generated by Django 5.2 on 2025-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, help_text="Unique email prefix for receiving emails (e.g., 'acme' will become acme@yourservice.com)", max_length=255, null=True, unique=True),
        ),
    ]
