# Generated by Django 5.2 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='openai_assistant_id',
            field=models.CharField(blank=True, help_text='OpenAI Assistant ID for this company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='openai_vector_store_id',
            field=models.CharField(blank=True, help_text='OpenAI Vector Store ID for this company', max_length=255, null=True),
        ),
    ]
