# Generated by Django 5.2 on 2025-05-04 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlySignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Early Signup',
                'verbose_name_plural': 'Early Signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
