# Generated by Django 5.2 on 2025-04-21 08:03

import django.db.models.deletion
import django.utils.timezone
import mail_receiver.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_meetingtranscript'),
        ('datasilo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.EmailField(max_length=255)),
                ('recipient', models.EmailField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('body_plain', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('stripped_text', models.TextField(blank=True)),
                ('stripped_html', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('mailgun_timestamp', models.IntegerField(blank=True, null=True)),
                ('mailgun_id', models.CharField(blank=True, max_length=255)),
                ('meeting_created', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_silo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to='datasilo.datasilo')),
                ('meeting_transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='agents.meetingtranscript')),
            ],
            options={
                'verbose_name': 'Incoming Email',
                'verbose_name_plural': 'Incoming Emails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=mail_receiver.models.email_attachment_path)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_attachments', to='datasilo.datafile')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_receiver.incomingemail')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
            },
        ),
    ]
